// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXz26FEAOzcDegn7Q1r9z8dd_WNI4NLJ0',
    appId: '1:920257285665:web:a307c79a2c293a51e59d60',
    messagingSenderId: '920257285665',
    projectId: 'iot663',
    authDomain: 'iot663.firebaseapp.com',
    storageBucket: 'iot663.firebasestorage.app',
    measurementId: 'G-GHP3X44GS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqsyqz_FXXQ8f8ytSWVzm4CshKLNaYiUM',
    appId: '1:920257285665:android:be8c3b0b66aaeff5e59d60',
    messagingSenderId: '920257285665',
    projectId: 'iot663',
    storageBucket: 'iot663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzdUCqjmzLJcdzTWUKBvGc_i-DMr1Mh0',
    appId: '1:920257285665:ios:17265bf9a91662d4e59d60',
    messagingSenderId: '920257285665',
    projectId: 'iot663',
    storageBucket: 'iot663.firebasestorage.app',
    iosBundleId: 'com.example.petrolCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzdUCqjmzLJcdzTWUKBvGc_i-DMr1Mh0',
    appId: '1:920257285665:ios:17265bf9a91662d4e59d60',
    messagingSenderId: '920257285665',
    projectId: 'iot663',
    storageBucket: 'iot663.firebasestorage.app',
    iosBundleId: 'com.example.petrolCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXz26FEAOzcDegn7Q1r9z8dd_WNI4NLJ0',
    appId: '1:920257285665:web:10f5f824095dbc74e59d60',
    messagingSenderId: '920257285665',
    projectId: 'iot663',
    authDomain: 'iot663.firebaseapp.com',
    storageBucket: 'iot663.firebasestorage.app',
    measurementId: 'G-CG0M0K2CG0',
  );

}