// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeNCsFhV18PNSaQSqYL6a375yBHWd6n0',
    appId: '1:662648386054:web:e0c7bc11649de9b90fc987',
    messagingSenderId: '662648386054',
    projectId: 'iot-63-8a438',
    authDomain: 'iot-63-8a438.firebaseapp.com',
    storageBucket: 'iot-63-8a438.firebasestorage.app',
    measurementId: 'G-5634E8SVJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLq-Iu2vH_H6l1BSYLnGZR0glPhXcYCpI',
    appId: '1:662648386054:android:60c837571cc74e740fc987',
    messagingSenderId: '662648386054',
    projectId: 'iot-63-8a438',
    storageBucket: 'iot-63-8a438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifzNF1GCpKhcS4KR-lUk41jNhaTCnlr0',
    appId: '1:662648386054:ios:9f76c00fec1282320fc987',
    messagingSenderId: '662648386054',
    projectId: 'iot-63-8a438',
    storageBucket: 'iot-63-8a438.firebasestorage.app',
    iosBundleId: 'com.example.petrolCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifzNF1GCpKhcS4KR-lUk41jNhaTCnlr0',
    appId: '1:662648386054:ios:9f76c00fec1282320fc987',
    messagingSenderId: '662648386054',
    projectId: 'iot-63-8a438',
    storageBucket: 'iot-63-8a438.firebasestorage.app',
    iosBundleId: 'com.example.petrolCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfeNCsFhV18PNSaQSqYL6a375yBHWd6n0',
    appId: '1:662648386054:web:f665e0832172c24b0fc987',
    messagingSenderId: '662648386054',
    projectId: 'iot-63-8a438',
    authDomain: 'iot-63-8a438.firebaseapp.com',
    storageBucket: 'iot-63-8a438.firebasestorage.app',
    measurementId: 'G-7VJ89RBDM3',
  );
}
